export const
    ID = 'ID',
    ACCESS_TOKEN = 'ACCESS_TOKEN',
    TEMPORARY_TOKEN = 'TEMPORARY_TOKEN',
    REFRESH_TOKEN = 'REFRESH_TOKEN',
    ROLE = 'ROLE',
    STATUS = 'STATUS',
    EMAIL = 'EMAIL';