doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        server_version: '11'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        types:
            user_user_id:   'App\Model\User\Entity\Types\IdType'
            user_user_role: 'App\Model\User\Entity\Types\RoleType'
            core_learner_id: 'App\Model\Core\Entity\Learner\Types\IdType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Core/Entity'
                prefix: 'App\Model\Core\Entity'
                alias: Core