security:
    encoders:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/v1/auth/login
            stateless: true
            anonymous: true
            json_login:
                check_path:  /api/v1/auth/login
                username_path: email
                remember_me: true
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        register:
            pattern:  ^/api/v1/auth/register
            stateless: true
            anonymous: true
        doc:
            pattern:  ^/api/v1/doc
            stateless: true
            anonymous: true
        refresh:
            pattern:  ^/api/v1/auth/token/refresh
            stateless: true
            anonymous: true
        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/v1/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/auth/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }