controllers:
  resource: '../src/Controller/'
  type:     annotation

#AuthController
login:
  path: /api/v1/auth/login
  controller: App\Controller\AuthController::login
  methods:  [POST]
register:
  path: /api/v1/auth/register
  controller: App\Controller\AuthController::register
  methods: [POST]
register_confirm:
  path: /api/v1/auth/register/confirm
  controller: App\Controller\AuthController::registerConfirm
  methods: [POST]
password_reset:
  path: /api/v1/auth/password/reset
  controller: App\Controller\AuthController::passwordReset
  methods: [POST]
refresh_token:
  path: /api/v1/auth/token/refresh
  controller: App\Controller\AuthController::refresh
  methods: [POST]

#Documentation
app.swagger_ui:
  path: /api/v1/doc
  methods: [GET]
  controller: nelmio_api_doc.controller.swagger_ui


# REST controllers
decks:
  type: rest
  resource: App\Controller\Rest\DeckController

card:
  type: rest
  resource: App\Controller\Rest\CardController

user:
  type: rest
  resource: App\Controller\Rest\UserController

